version: "3.8"

services:
  flask:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py
